/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'home-page': HomePage;
    resources: Resource;
    'contact-page': ContactPage;
    'contact-submissions': ContactSubmission;
    'products-page': ProductsPage;
    'customized-model-page': CustomizedModelPage;
    'customized-model-submissions': CustomizedModelSubmission;
    'workshops-page': WorkshopsPage;
    'training-courses-page': TrainingCoursesPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'products-page': ProductsPageSelect<false> | ProductsPageSelect<true>;
    'customized-model-page': CustomizedModelPageSelect<false> | CustomizedModelPageSelect<true>;
    'customized-model-submissions': CustomizedModelSubmissionsSelect<false> | CustomizedModelSubmissionsSelect<true>;
    'workshops-page': WorkshopsPageSelect<false> | WorkshopsPageSelect<true>;
    'training-courses-page': TrainingCoursesPageSelect<false> | TrainingCoursesPageSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  title: string;
  description?: string | null;
  sections?:
    | (
        | {
            headline: string;
            lede: string;
            ticks?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            primaryCTA?: {
              text?: string | null;
              link?: string | null;
            };
            secondaryCTA?: {
              text?: string | null;
              link?: string | null;
            };
            mainImage?: (number | null) | Media;
            mainImageUrl?: string | null;
            cardImage1?: (number | null) | Media;
            cardImage1Url?: string | null;
            cardImage2?: (number | null) | Media;
            cardImage2Url?: string | null;
            carouselImages?:
              | {
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            partnersList?:
              | {
                  logo?: (number | null) | Media;
                  logoUrl?: string | null;
                  name?: string | null;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partners';
          }
        | {
            title: string;
            productsList?:
              | {
                  title: string;
                  slug: string;
                  variant?: string | null;
                  price: string;
                  gstNote?: string | null;
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  alt?: string | null;
                  cartUrl?: string | null;
                  detailsUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'products';
          }
        | {
            title: string;
            subtitle?: string | null;
            detailsList?:
              | {
                  category: string;
                  title: string;
                  description: string;
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'true-to-life-details';
          }
        | {
            title: string;
            workshopsList?:
              | {
                  title: string;
                  category: 'temporal' | 'sinus' | 'larynx';
                  tagline?: string | null;
                  meta: string;
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  alt?: string | null;
                  brochureUrl?: string | null;
                  registrationUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'workshops';
          }
        | {
            tag?: string | null;
            title?: string | null;
            description?: string | null;
            collageImage?: (number | null) | Media;
            collageImageUrl?: string | null;
            gallery?:
              | {
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'workshop-glimpses';
          }
        | {
            title?: string | null;
            image?: (number | null) | Media;
            imageUrl?: string | null;
            checkList?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-artificial-bone';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            facultyList?:
              | {
                  initials: string;
                  name: string;
                  role: string;
                  bio: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faculty';
          }
        | {
            feedbackTitle?: string | null;
            feedbackList?:
              | {
                  quote: string;
                  author: string;
                  id?: string | null;
                }[]
              | null;
            storiesTitle?: string | null;
            storiesList?:
              | {
                  quote: string;
                  author: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title?: string | null;
            variantsList?:
              | {
                  code: string;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bone-variants';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            submitEmail?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lead-form';
          }
        | {
            tag?: string | null;
            title?: string | null;
            postsList?:
              | {
                  category: string;
                  title: string;
                  excerpt: string;
                  meta?: string | null;
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  sections?:
    | (
        | {
            crumbHomeText?: string | null;
            crumbCurrentText?: string | null;
            title?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resources-hero';
          }
        | {
            title?: string | null;
            points?:
              | {
                  num: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-simulation';
          }
        | {
            title?: string | null;
            features?:
              | {
                  num: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'model-features';
          }
        | {
            title?: string | null;
            procedures?:
              | {
                  name: string;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'temporal-bone-procedures';
          }
        | {
            title?: string | null;
            procedures?:
              | {
                  name: string;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sinus-procedures';
          }
        | {
            title?: string | null;
            procedures?:
              | {
                  name: string;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'larynx-procedures';
          }
        | {
            title?: string | null;
            variantsList?:
              | {
                  code: string;
                  title: string;
                  desc: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'variants';
          }
        | {
            title?: string | null;
            quote: string;
            doctorName?: string | null;
            doctorTitle?: string | null;
            image?: (number | null) | Media;
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doctor-acknowledgment';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  title: string;
  heroDescription?: string | null;
  indianQueries?: {
    title?: string | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  internationalQueries?: {
    title?: string | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  address?: {
    title?: string | null;
    text?: string | null;
  };
  formDisclaimer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  firstName: string;
  lastName?: string | null;
  country?: string | null;
  mobile?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page".
 */
export interface ProductsPage {
  id: number;
  title: string;
  hero?: {
    crumbHomeText?: string | null;
    crumbCurrentText?: string | null;
    title?: string | null;
    description?: string | null;
  };
  families?:
    | {
        familyId?: string | null;
        title: string;
        subtitle?: string | null;
        isAlt?: boolean | null;
        items?:
          | {
              name: string;
              badge?: string | null;
              image?: (number | null) | Media;
              imageUrl?: string | null;
              description?: string | null;
              bulletPoints?:
                | {
                    point?: string | null;
                    id?: string | null;
                  }[]
                | null;
              primaryButton?: {
                text?: string | null;
                link?: string | null;
              };
              secondaryButton?: {
                text?: string | null;
                link?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  stageComparison?: {
    title?: string | null;
    tiers?:
      | {
          tier: string;
          models: string;
          builtFor: string;
          typicalUse: string;
          id?: string | null;
        }[]
      | null;
    footerNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customized-model-page".
 */
export interface CustomizedModelPage {
  id: number;
  title: string;
  heroDescription?: string | null;
  dicomHelpText?: string | null;
  dicomFormatInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customized-model-submissions".
 */
export interface CustomizedModelSubmission {
  id: number;
  firstName: string;
  academicQualification: string;
  email: string;
  iMessageNo: string;
  whatsAppNo: string;
  viberNo: string;
  institutionName: string;
  address: string;
  state: string;
  city: string;
  country: string;
  pincode: string;
  file?: (number | null) | Media;
  fileName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops-page".
 */
export interface WorkshopsPage {
  id: number;
  title: string;
  heroDescription?: string | null;
  glimpses?: {
    image?: (number | null) | Media;
    imageUrl?: string | null;
    caption?: string | null;
    brochureFile?: (number | null) | Media;
    brochureUrl?: string | null;
  };
  temporalHeading?: string | null;
  sinusHeading?: string | null;
  larynxHeading?: string | null;
  temporalWorkshops?:
    | {
        title: string;
        tagline?: string | null;
        meta?: string | null;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        alt?: string | null;
        brochureFile?: (number | null) | Media;
        brochureUrl?: string | null;
        registrationUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  sinusWorkshops?:
    | {
        title: string;
        tagline?: string | null;
        meta?: string | null;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        alt?: string | null;
        brochureFile?: (number | null) | Media;
        brochureUrl?: string | null;
        registrationUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  larynxWorkshops?:
    | {
        title: string;
        tagline?: string | null;
        meta?: string | null;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        alt?: string | null;
        brochureFile?: (number | null) | Media;
        brochureUrl?: string | null;
        registrationUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  larynxStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-courses-page".
 */
export interface TrainingCoursesPage {
  id: number;
  title: string;
  heroDescription?: string | null;
  managementTeamTitle?: string | null;
  managementTeam?:
    | {
        initials: string;
        name: string;
        role: string;
        bio: string;
        photo?: (number | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  coursesSeriesTitle?: string | null;
  coursesSeriesDescription?: string | null;
  courses?:
    | {
        category: string;
        title: string;
        why: string;
        procedures?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        fmt: string;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        brochureFile?: (number | null) | Media;
        brochureUrl?: string | null;
        registrationUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  whyArtificialBone?: {
    title?: string | null;
    image?: (number | null) | Media;
    imageUrl?: string | null;
    checkList?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'home-page';
        value: number | HomePage;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'contact-page';
        value: number | ContactPage;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'products-page';
        value: number | ProductsPage;
      } | null)
    | ({
        relationTo: 'customized-model-page';
        value: number | CustomizedModelPage;
      } | null)
    | ({
        relationTo: 'customized-model-submissions';
        value: number | CustomizedModelSubmission;
      } | null)
    | ({
        relationTo: 'workshops-page';
        value: number | WorkshopsPage;
      } | null)
    | ({
        relationTo: 'training-courses-page';
        value: number | TrainingCoursesPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              lede?: T;
              ticks?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              primaryCTA?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              mainImage?: T;
              mainImageUrl?: T;
              cardImage1?: T;
              cardImage1Url?: T;
              cardImage2?: T;
              cardImage2Url?: T;
              carouselImages?:
                | T
                | {
                    image?: T;
                    imageUrl?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partners?:
          | T
          | {
              title?: T;
              partnersList?:
                | T
                | {
                    logo?: T;
                    logoUrl?: T;
                    name?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        products?:
          | T
          | {
              title?: T;
              productsList?:
                | T
                | {
                    title?: T;
                    slug?: T;
                    variant?: T;
                    price?: T;
                    gstNote?: T;
                    image?: T;
                    imageUrl?: T;
                    alt?: T;
                    cartUrl?: T;
                    detailsUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'true-to-life-details'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              detailsList?:
                | T
                | {
                    category?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    imageUrl?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        workshops?:
          | T
          | {
              title?: T;
              workshopsList?:
                | T
                | {
                    title?: T;
                    category?: T;
                    tagline?: T;
                    meta?: T;
                    image?: T;
                    imageUrl?: T;
                    alt?: T;
                    brochureUrl?: T;
                    registrationUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'workshop-glimpses'?:
          | T
          | {
              tag?: T;
              title?: T;
              description?: T;
              collageImage?: T;
              collageImageUrl?: T;
              gallery?:
                | T
                | {
                    image?: T;
                    imageUrl?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'why-artificial-bone'?:
          | T
          | {
              title?: T;
              image?: T;
              imageUrl?: T;
              checkList?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faculty?:
          | T
          | {
              title?: T;
              subtitle?: T;
              facultyList?:
                | T
                | {
                    initials?: T;
                    name?: T;
                    role?: T;
                    bio?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              feedbackTitle?: T;
              feedbackList?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    id?: T;
                  };
              storiesTitle?: T;
              storiesList?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'bone-variants'?:
          | T
          | {
              title?: T;
              variantsList?:
                | T
                | {
                    code?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'lead-form'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              submitEmail?: T;
              id?: T;
              blockName?: T;
            };
        blog?:
          | T
          | {
              tag?: T;
              title?: T;
              postsList?:
                | T
                | {
                    category?: T;
                    title?: T;
                    excerpt?: T;
                    meta?: T;
                    image?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        'resources-hero'?:
          | T
          | {
              crumbHomeText?: T;
              crumbCurrentText?: T;
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'why-simulation'?:
          | T
          | {
              title?: T;
              points?:
                | T
                | {
                    num?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'model-features'?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    num?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'temporal-bone-procedures'?:
          | T
          | {
              title?: T;
              procedures?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        'sinus-procedures'?:
          | T
          | {
              title?: T;
              procedures?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        'larynx-procedures'?:
          | T
          | {
              title?: T;
              procedures?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        variants?:
          | T
          | {
              title?: T;
              variantsList?:
                | T
                | {
                    code?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'doctor-acknowledgment'?:
          | T
          | {
              title?: T;
              quote?: T;
              doctorName?: T;
              doctorTitle?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  heroDescription?: T;
  indianQueries?:
    | T
    | {
        title?: T;
        name?: T;
        email?: T;
        phone?: T;
      };
  internationalQueries?:
    | T
    | {
        title?: T;
        name?: T;
        email?: T;
        phone?: T;
      };
  address?:
    | T
    | {
        title?: T;
        text?: T;
      };
  formDisclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  country?: T;
  mobile?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page_select".
 */
export interface ProductsPageSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        crumbHomeText?: T;
        crumbCurrentText?: T;
        title?: T;
        description?: T;
      };
  families?:
    | T
    | {
        familyId?: T;
        title?: T;
        subtitle?: T;
        isAlt?: T;
        items?:
          | T
          | {
              name?: T;
              badge?: T;
              image?: T;
              imageUrl?: T;
              description?: T;
              bulletPoints?:
                | T
                | {
                    point?: T;
                    id?: T;
                  };
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  stageComparison?:
    | T
    | {
        title?: T;
        tiers?:
          | T
          | {
              tier?: T;
              models?: T;
              builtFor?: T;
              typicalUse?: T;
              id?: T;
            };
        footerNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customized-model-page_select".
 */
export interface CustomizedModelPageSelect<T extends boolean = true> {
  title?: T;
  heroDescription?: T;
  dicomHelpText?: T;
  dicomFormatInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customized-model-submissions_select".
 */
export interface CustomizedModelSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  academicQualification?: T;
  email?: T;
  iMessageNo?: T;
  whatsAppNo?: T;
  viberNo?: T;
  institutionName?: T;
  address?: T;
  state?: T;
  city?: T;
  country?: T;
  pincode?: T;
  file?: T;
  fileName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshops-page_select".
 */
export interface WorkshopsPageSelect<T extends boolean = true> {
  title?: T;
  heroDescription?: T;
  glimpses?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        caption?: T;
        brochureFile?: T;
        brochureUrl?: T;
      };
  temporalHeading?: T;
  sinusHeading?: T;
  larynxHeading?: T;
  temporalWorkshops?:
    | T
    | {
        title?: T;
        tagline?: T;
        meta?: T;
        image?: T;
        imageUrl?: T;
        alt?: T;
        brochureFile?: T;
        brochureUrl?: T;
        registrationUrl?: T;
        id?: T;
      };
  sinusWorkshops?:
    | T
    | {
        title?: T;
        tagline?: T;
        meta?: T;
        image?: T;
        imageUrl?: T;
        alt?: T;
        brochureFile?: T;
        brochureUrl?: T;
        registrationUrl?: T;
        id?: T;
      };
  larynxWorkshops?:
    | T
    | {
        title?: T;
        tagline?: T;
        meta?: T;
        image?: T;
        imageUrl?: T;
        alt?: T;
        brochureFile?: T;
        brochureUrl?: T;
        registrationUrl?: T;
        id?: T;
      };
  larynxStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-courses-page_select".
 */
export interface TrainingCoursesPageSelect<T extends boolean = true> {
  title?: T;
  heroDescription?: T;
  managementTeamTitle?: T;
  managementTeam?:
    | T
    | {
        initials?: T;
        name?: T;
        role?: T;
        bio?: T;
        photo?: T;
        imageUrl?: T;
        id?: T;
      };
  coursesSeriesTitle?: T;
  coursesSeriesDescription?: T;
  courses?:
    | T
    | {
        category?: T;
        title?: T;
        why?: T;
        procedures?:
          | T
          | {
              text?: T;
              id?: T;
            };
        fmt?: T;
        image?: T;
        imageUrl?: T;
        brochureFile?: T;
        brochureUrl?: T;
        registrationUrl?: T;
        id?: T;
      };
  whyArtificialBone?:
    | T
    | {
        title?: T;
        image?: T;
        imageUrl?: T;
        checkList?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  announcement: {
    text: string;
    linkText: string;
    linkUrl: string;
  };
  logo?: (number | null) | Media;
  logoUrl?: string | null;
  searchPlaceholder?: string | null;
  navItems?:
    | {
        label: string;
        url?: string | null;
        hasDropdown?: boolean | null;
        dropdownItems?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  buyNowButton?: {
    text?: string | null;
    url?: string | null;
  };
  cartUrl?: string | null;
  loginButton?: {
    text?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  logoUrl?: string | null;
  quickLinksTitle?: string | null;
  quickLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  indianQuery?: {
    title?: string | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  internationalQuery?: {
    title?: string | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  address?: {
    title?: string | null;
    text?: string | null;
  };
  about?: string | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        text?: T;
        linkText?: T;
        linkUrl?: T;
      };
  logo?: T;
  logoUrl?: T;
  searchPlaceholder?: T;
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        hasDropdown?: T;
        dropdownItems?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  buyNowButton?:
    | T
    | {
        text?: T;
        url?: T;
      };
  cartUrl?: T;
  loginButton?:
    | T
    | {
        text?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  logoUrl?: T;
  quickLinksTitle?: T;
  quickLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  indianQuery?:
    | T
    | {
        title?: T;
        name?: T;
        email?: T;
        phone?: T;
      };
  internationalQuery?:
    | T
    | {
        title?: T;
        name?: T;
        email?: T;
        phone?: T;
      };
  address?:
    | T
    | {
        title?: T;
        text?: T;
      };
  about?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}